<li>
    <a href="#"><i class="glyphicon glyphicon-dashboard"></i> Home</a>
</li>
<li>
    <a href="#"><i class="glyphicon glyphicon-star"></i> Products</a>
</li>
<li>
    <a href="#"><i class="glyphicon glyphicon-tag"></i> Brands</a>
</li>
<li>
    <a href="#"><i class="glyphicon glyphicon-bookmark"></i> Category</a>
</li>
<li>
    <a href="#"><i class="glyphicon glyphicon-list-alt"></i> Orders</a>
</li>
<li>
    <a href="#"><i class="glyphicon glyphicon-eye-open"></i> Support</a>
</li>
<li>
    <a href="#"><i class="glyphicon glyphicon-user"></i> Profile</a>
</li>